<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Attachment;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class AttachmentController extends Controller
{
    public function index(Request $request)
    {
        $attachments = Attachment::orderBy('created_at', 'desc')
            ->orderBy('id', 'desc')
            ->with('entry')
            ->paginate();

        return view('admin.attachments.index', compact('attachments'));
    }

    public function store(Request $request)
    {
        $validated = $request->validate([
            'file' => 'required|file',
        ]);

        /** @todo Base the extension off the actual MIME type. */
        $filename = $validated['file']->getClientOriginalName();
        $filename = Str::limit(
            preg_replace('~.' . pathinfo($filename, PATHINFO_EXTENSION) . '$~', '', $filename),
            250,
            ''
        ) . '.' . pathinfo($filename, PATHINFO_EXTENSION);

        $path = $validated['file']->storeAs(
            gmdate('Y/m'), // Add year and month, WordPress-style.
            $filename,
            'public'
        );

        $attachment = Attachment::updateOrCreate(
            [
                'path' => $path,
                'user_id' => $request->user()->id,
            ],
            $validated
        );

        $this->createThumbnails($attachment);

        return view('admin.attachments.edit', compact('attachment'));
    }

    public function edit(Attachment $attachment)
    {
        $attachment->load('entry');

        return view('admin.attachments.edit', compact('attachment'));
    }

    public function update(Request $request, Attachment $attachment)
    {
        $validated = $request->validate([
            'name' => 'nullable|max:250',
            'alt' => 'nullable|max:250',
            'caption' => 'nullable|max:250',
        ]);

        $attachment->update($validated);

        return back()
            ->with('success', __('Changes saved!'));
        ;
    }

    public function destroy(Attachment $attachment)
    {
        $files = array_values(array_merge(
            (array) $attachment->path, // Original image.
            $attachment->meta['sizes'] ?? [] // Autogenerated thumbnails, if any.
        ));

        Storage::disk('public')->delete($files);

        $attachment->delete();

        return back()
            ->with('success', __('Deleted!'));
    }

    protected function createThumbnails(Attachment $attachment)
    {

        if (! class_exists('Imagick')) {
            Log::error('Imagick not found');

            return;
        }

        $fullPath = Storage::disk('public')->path($attachment->path);

        // Load image.
        $imagick = new \Imagick();
        $imagick->readimage($fullPath);

        $width = $imagick->getImageWidth();
        $height = $imagick->getImageHeight();

        $sizes = [];

        foreach (Attachment::SIZES as $size => $newWidth) {
            if ($newWidth >= $width) {
                // Avoid generating larger versions.
                continue;
            }

            $copy = clone $imagick;

            if ($size === 'thumbnail') {
                // Always crop thumbnails.
                $newHeight = $newWidth;
                $copy->cropThumbnailImage($newWidth, $newHeight);
            } else {
                $newHeight = (int) $height * $newWidth / $width;
                $copy->resizeImage($newWidth, $newHeight, \Imagick::FILTER_CATROM, 1);
            }

            $copy->setImagePage(0, 0, 0, 0);

            $fullThumbnailPath = sprintf(
                '%s-%dx%d.%s',
                preg_replace('~.' . pathinfo($fullPath, PATHINFO_EXTENSION) . '$~', '', $fullPath),
                $newWidth,
                $newHeight,
                pathinfo($fullPath, PATHINFO_EXTENSION)
            );

            $copy->writeImage($fullThumbnailPath);
            $copy->destroy();

            $relativeThumbnailPath = preg_replace(
                '~^' . Storage::disk('public')->path('') . '~',
                '',
                $fullThumbnailPath
            );

            $sizes[$size] = $relativeThumbnailPath;
        }

        $imagick->destroy();

        $attachment->updateMeta(
            ['width', 'height', 'sizes'],
            [$width, $height, $sizes]
        );
    }
}
